defmodule FerricstoreServer.Acl.Persistence do
  @moduledoc false

  alias FerricstoreServer.Acl.FileParser
  alias FerricstoreServer.Acl.Formatter
  alias FerricstoreServer.Acl.Tables

  @acl_filename "acl.conf"
  @max_file_size 50_000_000

  @spec acl_file_path(binary()) :: binary()
  def acl_file_path(data_dir), do: Path.join(data_dir, @acl_filename)

  @spec save(binary()) :: :ok | {:error, binary()}
  def save(data_dir) do
    path = acl_file_path(data_dir)
    tmp = path <> ".tmp.#{System.unique_integer([:positive])}"

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    header =
      "# FerricStore ACL configuration\n" <>
        "# Generated by ACL SAVE at #{DateTime.utc_now() |> DateTime.to_iso8601()}\n\n"

    lines =
      Tables.active_table()
      |> :ets.tab2list()
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map_join("\n", &Formatter.format_user_for_file/1)

    contents = header <> lines <> "\n"

    with :ok <- Ferricstore.FS.mkdir_p(data_dir),
         :ok <- File.write(tmp, contents),
         :ok <- File.chmod(tmp, 0o600),
         :ok <- fsync_file(tmp),
         :ok <- Ferricstore.FS.rename(tmp, path),
         _ <- Ferricstore.Bitcask.NIF.v2_fsync_dir(data_dir) do
      :ok
    else
      {:error, reason} ->
        _ = Ferricstore.FS.rm(tmp)
        {:error, "ERR ACL save failed: #{inspect(reason)}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec load(binary()) :: :ok | {:error, binary()}
  def load(data_dir) do
    with {:ok, contents} <- read_file_contents(data_dir) do
      load_contents(contents)
    end
  catch
    {:error, _} = err -> err
  end

  @spec read_file_contents(binary()) :: {:ok, binary()} | {:error, binary()}
  def read_file_contents(data_dir) do
    path = acl_file_path(data_dir)

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    case File.read(path) do
      {:ok, contents} ->
        if byte_size(contents) > @max_file_size do
          {:error, "ERR ACL file too large (#{byte_size(contents)} bytes, max #{@max_file_size})"}
        else
          {:ok, contents}
        end

      {:error, :enoent} ->
        {:error, "ERR There is no ACL file to load"}

      {:error, :eacces} ->
        {:error, "ERR Permission denied reading ACL file"}

      {:error, reason} ->
        {:error, "ERR Cannot read ACL file: #{inspect(reason)}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec validate_contents(binary()) :: :ok | {:error, binary()}
  def validate_contents(contents) do
    case FileParser.parse(contents) do
      {:ok, users} ->
        if Enum.any?(users, fn {name, _} -> name == "default" end) do
          :ok
        else
          {:error, "ERR ACL file must contain a 'default' user definition"}
        end

      {:error, _} = err ->
        err
    end
  end

  @spec load_contents(binary()) :: :ok | {:error, binary()}
  def load_contents(contents) do
    if byte_size(contents) > @max_file_size do
      {:error, "ERR ACL file too large (#{byte_size(contents)} bytes, max #{@max_file_size})"}
    else
      case FileParser.parse(contents) do
        {:ok, users} ->
          unless Enum.any?(users, fn {name, _} -> name == "default" end) do
            throw({:error, "ERR ACL file must contain a 'default' user definition"})
          end

          Tables.replace_acl_snapshot(users)

        {:error, _} = err ->
          err
      end
    end
  catch
    {:error, _} = err -> err
  end

  @spec auto_load_from_file(binary()) :: :ok | {:error, :enoent} | {:error, binary()}
  def auto_load_from_file(data_dir) do
    path = acl_file_path(data_dir)

    case File.read(path) do
      {:ok, contents} ->
        if byte_size(contents) > @max_file_size do
          {:error, "ACL file too large"}
        else
          case FileParser.parse(contents) do
            {:ok, users} ->
              if Enum.any?(users, fn {name, _} -> name == "default" end) do
                Tables.replace_acl_snapshot(users)
              else
                {:error, "ACL file missing 'default' user"}
              end

            {:error, reason} ->
              {:error, reason}
          end
        end

      {:error, :enoent} ->
        {:error, :enoent}

      {:error, reason} ->
        {:error, "Cannot read ACL file: #{inspect(reason)}"}
    end
  end

  defp validate_acl_path(path, data_dir) do
    abs_path = Path.expand(path)
    abs_dir = Path.expand(data_dir)

    cond do
      not (String.starts_with?(abs_path, abs_dir <> "/") or abs_path == abs_dir) ->
        {:error, "ERR ACL file path escapes data directory"}

      symlink?(path) ->
        {:error, "ERR ACL file path is a symlink, refusing for security"}

      true ->
        :ok
    end
  end

  defp symlink?(path) do
    case File.lstat(path) do
      {:ok, %{type: :symlink}} -> true
      _ -> false
    end
  end

  defp fsync_file(path) do
    case :file.open(String.to_charlist(path), [:read, :write]) do
      {:ok, fd} ->
        result = :file.sync(fd)
        :file.close(fd)
        result

      {:error, reason} ->
        {:error, reason}
    end
  end
end
