defmodule FerricstoreServer.Acl.Persistence do
  @moduledoc false

  alias FerricstoreServer.Acl.FileParser
  alias FerricstoreServer.Acl.Formatter
  alias FerricstoreServer.Acl.AuthEpoch
  alias FerricstoreServer.Acl.Tables

  @acl_filename "acl.conf"
  @max_file_size 50_000_000

  @spec acl_file_path(binary()) :: binary()
  def acl_file_path(data_dir), do: Path.join(data_dir, @acl_filename)

  @spec save(binary(), non_neg_integer()) :: :ok | {:error, binary()}
  def save(data_dir, auth_epoch) do
    path = acl_file_path(data_dir)
    tmp = path <> ".tmp.#{System.unique_integer([:positive])}"

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    header =
      "# FerricStore ACL configuration\n" <>
        "# Generated by ACL SAVE at #{DateTime.utc_now() |> DateTime.to_iso8601()}\n" <>
        AuthEpoch.global_metadata(auth_epoch) <> "\n\n"

    lines =
      Tables.active_table()
      |> :ets.tab2list()
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map_join("\n", fn {username, user} = entry ->
        AuthEpoch.user_metadata(username, user) <> "\n" <> Formatter.format_user_for_file(entry)
      end)

    contents = header <> lines <> "\n"

    with :ok <- Ferricstore.FS.mkdir_p(data_dir),
         :ok <- File.write(tmp, contents),
         :ok <- File.chmod(tmp, 0o600),
         :ok <- fsync_file(tmp),
         :ok <- Ferricstore.FS.rename(tmp, path),
         _ <- Ferricstore.Bitcask.NIF.v2_fsync_dir(data_dir) do
      :ok
    else
      {:error, reason} ->
        _ = Ferricstore.FS.rm(tmp)
        {:error, "ERR ACL save failed: #{inspect(reason)}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec load(binary(), non_neg_integer()) ::
          {:ok, non_neg_integer()} | {:error, binary()}
  def load(data_dir, live_epoch) do
    with {:ok, contents} <- read_file_contents(data_dir) do
      load_contents(contents, live_epoch)
    end
  catch
    {:error, _} = err -> err
  end

  @spec read_file_contents(binary()) :: {:ok, binary()} | {:error, binary()}
  def read_file_contents(data_dir) do
    path = acl_file_path(data_dir)

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    case Ferricstore.FS.read_nofollow(path) do
      {:ok, contents} ->
        if byte_size(contents) > @max_file_size do
          {:error, "ERR ACL file too large (#{byte_size(contents)} bytes, max #{@max_file_size})"}
        else
          {:ok, contents}
        end

      {:error, {:not_found, _}} ->
        {:error, "ERR There is no ACL file to load"}

      {:error, {:permission_denied, _}} ->
        {:error, "ERR Permission denied reading ACL file"}

      {:error, {:symlink, _}} ->
        {:error, "ERR ACL file path is a symlink, refusing for security"}

      {:error, {kind, reason}} ->
        {:error, "ERR Cannot read ACL file: #{inspect({kind, reason})}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec validate_contents(binary()) :: :ok | {:error, binary()}
  def validate_contents(contents) do
    case FileParser.parse(contents) do
      {:ok, users} ->
        if Enum.any?(users, fn {name, _} -> name == "default" end) do
          :ok
        else
          {:error, "ERR ACL file must contain a 'default' user definition"}
        end

      {:error, _} = err ->
        err
    end
  end

  @spec load_contents(binary(), non_neg_integer()) ::
          {:ok, non_neg_integer()} | {:error, binary()}
  def load_contents(contents, live_epoch) do
    if byte_size(contents) > @max_file_size do
      {:error, "ERR ACL file too large (#{byte_size(contents)} bytes, max #{@max_file_size})"}
    else
      case FileParser.parse(contents) do
        {:ok, users} ->
          unless Enum.any?(users, fn {name, _} -> name == "default" end) do
            throw({:error, "ERR ACL file must contain a 'default' user definition"})
          end

          :ok = validate_user_limit!(users)
          {users, auth_epoch} = AuthEpoch.rebase(users, live_epoch)
          :ok = Tables.replace_acl_snapshot(users)
          {:ok, auth_epoch}

        {:error, _} = err ->
          err
      end
    end
  catch
    {:error, _} = err -> err
  end

  @spec auto_load_from_file(binary(), non_neg_integer()) ::
          {:ok, non_neg_integer()} | {:error, :enoent} | {:error, binary()}
  def auto_load_from_file(data_dir, live_epoch) do
    case read_file_contents(data_dir) do
      {:ok, contents} ->
        case FileParser.parse(contents) do
          {:ok, users} ->
            if Enum.any?(users, fn {name, _} -> name == "default" end) do
              with :ok <- validate_user_limit(users),
                   {:ok, users, auth_epoch} <- AuthEpoch.restore(contents, users, live_epoch) do
                :ok = Tables.replace_acl_snapshot(users)
                {:ok, auth_epoch}
              end
            else
              {:error, "ACL file missing 'default' user"}
            end

          {:error, reason} ->
            {:error, reason}
        end

      {:error, "ERR There is no ACL file to load"} ->
        {:error, :enoent}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp validate_user_limit!(users) do
    case validate_user_limit(users) do
      :ok -> :ok
      {:error, _reason} = error -> throw(error)
    end
  end

  defp validate_user_limit(users) when is_list(users) do
    max = Application.get_env(:ferricstore, :max_acl_users, 10_000)
    max = if is_integer(max) and max >= 0, do: max, else: 10_000

    if length(users) <= max do
      :ok
    else
      {:error, "ERR max ACL users reached (#{max})"}
    end
  end

  defp validate_acl_path(path, data_dir) do
    abs_path = Path.expand(path)
    abs_dir = Path.expand(data_dir)

    cond do
      not (String.starts_with?(abs_path, abs_dir <> "/") or abs_path == abs_dir) ->
        {:error, "ERR ACL file path escapes data directory"}

      symlink?(path) ->
        {:error, "ERR ACL file path is a symlink, refusing for security"}

      true ->
        :ok
    end
  end

  defp symlink?(path) do
    case File.lstat(path) do
      {:ok, %{type: :symlink}} -> true
      _ -> false
    end
  end

  defp fsync_file(path) do
    case :file.open(String.to_charlist(path), [:read, :write]) do
      {:ok, fd} ->
        result = :file.sync(fd)
        :file.close(fd)
        result

      {:error, reason} ->
        {:error, reason}
    end
  end
end
