defmodule FerricstoreServer.Acl.Persistence do
  @moduledoc false

  alias FerricstoreServer.Acl.FileParser
  alias FerricstoreServer.Acl.Formatter
  alias FerricstoreServer.Acl.AuthEpoch
  alias FerricstoreServer.Acl.Tables

  @acl_filename "acl.conf"
  @max_file_size 50_000_000

  @spec acl_file_path(binary()) :: binary()
  def acl_file_path(data_dir), do: Path.join(data_dir, @acl_filename)

  @spec save(binary(), non_neg_integer()) :: :ok | {:error, binary()}
  def save(data_dir, auth_epoch), do: save(data_dir, auth_epoch, [])

  @doc false
  @spec save(binary(), non_neg_integer(), keyword()) :: :ok | {:error, binary()}
  def save(data_dir, auth_epoch, opts) when is_list(opts) do
    path = acl_file_path(data_dir)
    tmp = path <> ".tmp.#{System.unique_integer([:positive])}"

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    entries =
      Tables.active_table()
      |> :ets.tab2list()

    generated_at = DateTime.utc_now() |> DateTime.to_iso8601()

    with {:ok, contents} <- build_contents(entries, auth_epoch, generated_at, @max_file_size),
         :ok <- Ferricstore.FS.mkdir_p(data_dir),
         :ok <- write_secure_temp(tmp, contents),
         :ok <- Ferricstore.FS.rename(tmp, path),
         :ok <- fsync_dir(data_dir, opts) do
      :ok
    else
      {:error, {:too_large, bytes, max_bytes}} ->
        {:error, "ERR ACL file too large (#{bytes} bytes, max #{max_bytes})"}

      {:error, reason} ->
        _ = Ferricstore.FS.rm(tmp)
        {:error, "ERR ACL save failed: #{inspect(reason)}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec read_file_contents(binary()) :: {:ok, binary()} | {:error, binary()}
  def read_file_contents(data_dir) do
    path = acl_file_path(data_dir)

    case validate_acl_path(path, data_dir) do
      :ok -> :ok
      {:error, _} = err -> throw(err)
    end

    case Ferricstore.FS.read_nofollow(path, @max_file_size) do
      {:ok, contents} ->
        {:ok, contents}

      {:error, {:too_large, reason}} ->
        {:error, "ERR ACL file too large (#{reason})"}

      {:error, {:not_found, _}} ->
        {:error, "ERR There is no ACL file to load"}

      {:error, {:permission_denied, _}} ->
        {:error, "ERR Permission denied reading ACL file"}

      {:error, {:symlink, _}} ->
        {:error, "ERR ACL file path is a symlink, refusing for security"}

      {:error, {kind, reason}} ->
        {:error, "ERR Cannot read ACL file: #{inspect({kind, reason})}"}
    end
  catch
    {:error, _} = err -> err
  end

  @spec validate_contents(binary()) :: :ok | {:error, binary()}
  def validate_contents(contents) do
    case parse_contents(contents) do
      {:ok, _users} -> :ok
      {:error, _reason} = error -> error
    end
  end

  @spec parse_contents(binary()) :: {:ok, [{binary(), map()}]} | {:error, binary()}
  def parse_contents(contents) when is_binary(contents) do
    if byte_size(contents) > @max_file_size do
      {:error, "ERR ACL file too large (#{byte_size(contents)} bytes, max #{@max_file_size})"}
    else
      with {:ok, users} <- FileParser.parse(contents),
           :ok <- validate_default_user(users),
           :ok <- validate_user_limit(users) do
        {:ok, users}
      end
    end
  end

  def parse_contents(_contents), do: {:error, "ERR invalid ACL file contents"}

  @doc false
  @spec build_contents(
          [{binary(), map()}],
          non_neg_integer(),
          binary(),
          non_neg_integer()
        ) :: {:ok, iodata()} | {:error, {:too_large, non_neg_integer(), non_neg_integer()}}
  def build_contents(entries, auth_epoch, generated_at, max_bytes)
      when is_list(entries) and is_integer(auth_epoch) and auth_epoch >= 0 and
             is_binary(generated_at) and is_integer(max_bytes) and max_bytes >= 0 do
    header = [
      "# FerricStore ACL configuration\n",
      "# Generated by ACL SAVE at ",
      generated_at,
      "\n",
      AuthEpoch.global_metadata(auth_epoch),
      "\n\n"
    ]

    with {:ok, chunks, bytes} <- append_bounded([], 0, header, max_bytes),
         {:ok, chunks, bytes} <- append_entries(entries, chunks, bytes, max_bytes),
         {:ok, chunks, _bytes} <- append_bounded(chunks, bytes, "\n", max_bytes) do
      {:ok, Enum.reverse(chunks)}
    end
  end

  defp validate_default_user(users) do
    if Enum.any?(users, fn {name, _} -> name == "default" end) do
      :ok
    else
      {:error, "ERR ACL file must contain a 'default' user definition"}
    end
  end

  defp append_entries(entries, chunks, bytes, max_bytes) do
    entries
    |> Enum.sort_by(fn {name, _user} -> name end)
    |> Enum.with_index()
    |> Enum.reduce_while({:ok, chunks, bytes}, fn {{username, user} = entry, index},
                                                  {:ok, chunks, bytes} ->
      separator = if index == 0, do: [], else: "\n"

      rendered = [
        separator,
        AuthEpoch.user_metadata(username, user),
        "\n",
        Formatter.format_user_for_file(entry)
      ]

      case append_bounded(chunks, bytes, rendered, max_bytes) do
        {:ok, _chunks, _bytes} = next -> {:cont, next}
        {:error, _reason} = error -> {:halt, error}
      end
    end)
  end

  defp append_bounded(chunks, bytes, chunk, max_bytes) do
    next_bytes = bytes + IO.iodata_length(chunk)

    if next_bytes <= max_bytes do
      {:ok, [chunk | chunks], next_bytes}
    else
      {:error, {:too_large, next_bytes, max_bytes}}
    end
  end

  defp validate_user_limit(users) when is_list(users) do
    max = Application.get_env(:ferricstore, :max_acl_users, 10_000)
    max = if is_integer(max) and max >= 0, do: max, else: 10_000

    if length(users) <= max do
      :ok
    else
      {:error, "ERR max ACL users reached (#{max})"}
    end
  end

  defp validate_acl_path(path, data_dir) do
    abs_path = Path.expand(path)
    abs_dir = Path.expand(data_dir)

    cond do
      not (String.starts_with?(abs_path, abs_dir <> "/") or abs_path == abs_dir) ->
        {:error, "ERR ACL file path escapes data directory"}

      symlink?(path) ->
        {:error, "ERR ACL file path is a symlink, refusing for security"}

      true ->
        :ok
    end
  end

  defp symlink?(path) do
    case File.lstat(path) do
      {:ok, %{type: :symlink}} -> true
      _ -> false
    end
  end

  @doc false
  @spec write_secure_temp(binary(), iodata()) :: :ok | {:error, term()}
  def write_secure_temp(path, contents) when is_binary(path) do
    case File.open(path, [:write, :exclusive, :binary]) do
      {:ok, io} ->
        try do
          with :ok <- File.chmod(path, 0o600),
               :ok <- IO.binwrite(io, contents),
               :ok <- :file.sync(io) do
            :ok
          end
        rescue
          error -> {:error, error}
        catch
          kind, reason -> {:error, {kind, reason}}
        after
          _ = File.close(io)
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp fsync_dir(path, opts) do
    case Keyword.get(opts, :fsync_dir_fun) do
      fun when is_function(fun, 1) -> fun.(path)
      _ -> Ferricstore.Bitcask.NIF.v2_fsync_dir(path)
    end
  end
end
